### PR TITLE
Fixes #2941 Adds support for query builder reports

### LINKED ISSUE #2941: Add "Query Builder" language to query section of Report Builder
## Required Information

* [ x ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: ___6.5.13____
* [ x ] ACS AEM Commons Version: _5.3.0 (but presumably back in older, 4.5.x versions, too)____
* [ x ] Reproducible on Latest? yes

### Expected Behavior

When I add a query to a Report Builder report I have a choice of languages - JCR-SQL, JCR-SQL2, JCR-JQOM, and XPath (see attached image).  I would like to write my query in Query Builder syntax to take advantage of relativedaterange predicate.

People often develop queries in the Query Debugger using Query Builder language - it'd be nice to cut/paste a working, tested query into a report query.

### Actual Behavior

Query Builder syntax is not available in the combobox of available languages.

### Steps to Reproduce

Install latest version of ACS AEM Commons, create a report, edit the query and open the "Query Language" combobox. 

### Links

please add query builder language

### PR DESCRIPTION
**Pull request by klcodanr**

### CODE REVIEW

File: bundle/src/main/java/com/adobe/acs/commons/reports/models/QueryReportExecutor.java [hunk 1]
```diff
@@ -45,165 +46,242 @@
...
+            log.debug("Fetching results with limit {} and offset {}", limit, offset);
+            query.setHitsPerPage(limit);
+            query.setStart(offset);
+        } else {
+            log.debug("Fetching all results");
+        }
 
-      Stream<Resource> results = StreamSupport.stream(spliterator, false).map(n -> getResource(n, resolver));
+        SearchResult result = query.getResult();
+        Spliterator<Resource> spliterator = Spliterators.spliteratorUnknownSize(result.getResources(),
```
Comment (davidjgonzalez) [inline bundle/src/main/java/com/adobe/acs/commons/reports/models/QueryReportExecutor.java:141]: Do we have to worry about the leaking ResourceResolver in QB?

https://github.com/Adobe-Consulting-Services/acs-aem-samples/blob/master/core/src/main/java/com/adobe/acs/samples/search/querybuilder/impl/SampleQueryBuilder.java#L159-L198

Comment (adamcin) [reply bundle/src/main/java/com/adobe/acs/commons/reports/models/QueryReportExecutor.java]: @davidjgonzalez @klcodanr we've got this utility method that prevents the Query from creating its own ResourceResolver: https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/06d2c1c5e82545feabba8251e6f3a0ee503964e4/bundle/src/main/java/com/adobe/acs/commons/cqsearch/QueryUtil.java#L57

Comment (klcodanr) [reply bundle/src/main/java/com/adobe/acs/commons/reports/models/QueryReportExecutor.java]: I took a different approach to map the hits into resources rather than calling the getResource method. As far as I can tell this avoid creating the resource resolver since it's lazily created.

Comment (adamcin) [reply bundle/src/main/java/com/adobe/acs/commons/reports/models/QueryReportExecutor.java]: @klcodanr Ah, I see what you did there 👍
