### PR TITLE
#1026 - Synthetic Workflow support multiple processes of the same type

### LINKED ISSUE #1026: Synthetic Workflow - Does not support multiple WF Model steps of the same Process
The way Synthetic Workflow internally caches WF Process Metadata  is by the Process name in a Map which does not work when the Process name is a key, as it enforces a single Metadata map PER process name.

Synthetic WF should be updated to support multiple WF Steps of the SAME process, but with different Metadata Maps.

### PR DESCRIPTION
**Pull request by davidjgonzalez**
Fixes #1026

### CODE REVIEW

File: bundle/src/main/java/com/adobe/acs/commons/workflow/synthetic/impl/SyntheticWorkflowRunnerImpl.java [hunk 1]
```diff
@@ -341,6 +344,25 @@ private void runGraniteWorkflowProcess(Session session,
...
+     * @param workflowProcessIds the ordered list of workflow process id or labels
+     * @param processArgs the metadata map args, indexed by workflowProcessId
+     * @return the ordered list of SyntheticWorkflowSteps that represent the parameter data
+     */
+    private List<SyntheticWorkflowStep> convertToSyntheticWorkflowSteps(String[] workflowProcessIds,
+                                                                        WorkflowProcessIdType idType,
+                                                                        Map<String, Map<String, Object>> processArgs) {
+        final List<SyntheticWorkflowStep> workflowSteps = new ArrayList<>();
+
+        for (String workflowProcessId : workflowProcessIds) {
```
Comment (andyklimczak) [inline bundle/src/main/java/com/adobe/acs/commons/workflow/synthetic/impl/SyntheticWorkflowRunnerImpl.java]: could we use a stream().map here instead?

```
return workflowProcessIds
  .stream()
  .map(workflowProcessId -> getSyntheticWorkflowStep(workflowProcessId, idType, processArgs.get(workflowProcessId))
  .collect(Collectors.toList());
```

File: bundle/src/main/java/com/adobe/acs/commons/workflow/synthetic/SyntheticWorkflowStep.java [hunk 2]
```diff
@@ -0,0 +1,14 @@
+package com.adobe.acs.commons.workflow.synthetic;
```
Comment (justinedelson) [inline bundle/src/main/java/com/adobe/acs/commons/workflow/synthetic/SyntheticWorkflowStep.java]: missing license header

File: bundle/src/main/java/com/adobe/acs/commons/workflow/synthetic/package-info.java [hunk 3]
```diff
@@ -21,5 +21,5 @@
 /**
  * Synthetic AEM Workflow APIs.
  */
-@aQute.bnd.annotation.Version("2.0.0")
+@aQute.bnd.annotation.Version("3.0.0")
```
Comment (justinedelson) [inline bundle/src/main/java/com/adobe/acs/commons/workflow/synthetic/package-info.java]: is it possible to avoid this major package bump? I think `SyntheticWorkflowRunner` might be missing `@ProviderType`

**Comment by davidjgonzalez** [comment]
Thanks - should be ok now

**Comment by davidjgonzalez** [comment]
Odd; looks like the later commits are not updating.. closing/reopening to see if it resolves.

**Comment by davidjgonzalez** [comment]
GH is confused; the comments left for copyright and package-info are addresses (not sure why GH web ui is stale)
