### PR TITLE
Revert the resolver after a failing on-deploy script.

### LINKED ISSUE #2090: On-Deploy Framework commits changes made by failing scripts
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.3.3.0
* [ ] ACS AEM Commons Version: 3.17.4
* [ ] Reproducible on Latest? (haven't checked yet, but based on the code it should be)

### Expected Behavior

When an on-deploy script is being executed and an unhandled exception escapes from the execute() method, I expect that any uncommitted changes made through the provided resource resolver are discarded.

### Actual Behavior

When an exception escapes from an on-deploy script, the pending changes of the resource resolver are persisted.

### Steps to Reproduce

Below is a minimal script provider that demonstrates the issue. Once you deploy that provider into an AEM instance, you should see a node at "/content/should-not-see-me". This is a node created by a script just before throwing an exception. Since the script didn't commit its changes manually before throwing, it's expected that the changes are discarded and you don't see the new node.

```java
package com.example.issue.repro;

import java.util.Collections;
import java.util.List;

import org.apache.sling.api.resource.Resource;
import org.apache.sling.api.resource.ResourceResolver;
import org.osgi.service.component.annotations.Component;

import com.adobe.acs.commons.ondeploy.OnDeployScriptProvider;
import com.adobe.acs.commons.ondeploy.scripts.OnDeployScript;
import com.adobe.acs.commons.ondeploy.scripts.OnDeployScriptBase;

@Component
public class IssueReproOnDeployScriptProvider implements OnDeployScriptProvider {

  private static class FailingScript extends OnDeployScriptBase {

    @Override
    protected void execute() throws Exception {
      ResourceResolver resolver = getResourceResolver();
      Resource content = resolver.getResource("/content");
      resolver.create(content, "should-not-see-me", Collections.emptyMap());
      
      throw new IllegalStateException("Simulating script error");
    }
    
  }
  
  @Override
  public List<OnDeployScript> getScripts() {
    return Collections.singletonList(new FailingScript());
  }

}
```

### PR DESCRIPTION
**Pull request by csaboka**
This makes sure none of the pending changes are persisted into the repo.
Fixes #2090.

### CODE REVIEW

File: bundle/src/test/java/com/adobe/acs/commons/ondeploy/impl/OnDeployExecutorImplTest.java [hunk 1]
```diff
@@ -64,7 +65,7 @@
 
 public class OnDeployExecutorImplTest {
     @Rule
-    public final AemContext context = new AemContext(ResourceResolverType.JCR_MOCK);
+    public final AemContext context = new AemContext(ResourceResolverType.JCR_OAK);
```
Comment (csaboka) [inline bundle/src/test/java/com/adobe/acs/commons/ondeploy/impl/OnDeployExecutorImplTest.java]: I needed to switch the mock implementation because JCR Mock doesn't implement revert functionality.

**Comment by csaboka** [comment]
Guys, can I do anything to help getting this merged? It's a pretty simple change, has test coverage, and also had two approvals at one point (although maybe not from the right people because it still said merging is blocked when the approvals were there). I just want to make sure it's not something I forgot that causes this not to be merged yet.
