### PR TITLE
Resolve ClientLib before trying to get it with the HtmlLibraryManager

### LINKED ISSUE #2528: Versioned ClientLibs not working with Resource Resolver Mapping
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.6
* [ ] ACS AEM Commons Version: 4.11.2
* [ ] Reproducible on Latest? yes

### Expected Behavior

When the project contains a Resource Resolver Mapping to hide the clientlib technical path, the service should be able to find the correct path before trying to obtain the Library.

### Actual Behavior

The service is relying on the path found in the html and not trying to resolve it first.

### Steps to Reproduce

[1] Setup and instance 6.5.6 with the ACS versioned clientLibs on.
[2] Add a JCR Resource Resolver Mapping like /etc/designs/myproject-/
[3] Check if the md5 was added to the request

### Links

https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/rewriter/impl/VersionedClientlibsTransformerFactory.java#L276
It's failing on this line when is doing the getLibrary() with the incorrect path

### PR DESCRIPTION
**Pull request by pcastelog**
Resolves #2528

### CODE REVIEW

File: bundle/src/main/java/com/adobe/acs/commons/rewriter/impl/VersionedClientlibsTransformerFactory.java [hunk 1]
```diff
@@ -272,10 +274,26 @@ private String getVersionedPath(final String originalPath, final LibraryType lib
...
+    private String resolvePath(LibraryType libraryType, String libraryPath, ResourceResolver resourceResolver) {
+        String clientLibraryPath = resolvePathIfJcrMapping(libraryPath, resourceResolver);
+        if (StringUtils.isEmpty(clientLibraryPath)) {
+            clientLibraryPath = resolvePathIfProxied(libraryType, libraryPath, resourceResolver);
+        }
+        return clientLibraryPath;
+    }
+
+    private String resolvePathIfJcrMapping(String libraryPath, ResourceResolver resourceResolver) {
+        Resource libraryResource = resourceResolver.resolve(libraryPath);
```
Comment (kwin) [inline bundle/src/main/java/com/adobe/acs/commons/rewriter/impl/VersionedClientlibsTransformerFactory.java:290]: Please use the two argument version, as otherwise resolve may fail (as things like request headers cannot be taken into account): https://sling.apache.org/apidocs/sling11/org/apache/sling/api/resource/ResourceResolver.html#resolve-javax.servlet.http.HttpServletRequest-java.lang.String-

File: bundle/src/main/java/com/adobe/acs/commons/rewriter/impl/VersionedClientlibsTransformerFactory.java [hunk 2]
```diff
@@ -272,10 +274,26 @@ private String getVersionedPath(final String originalPath, final LibraryType lib
...
 
+    private String resolvePath(LibraryType libraryType, String libraryPath, ResourceResolver resourceResolver) {
+        String clientLibraryPath = resolvePathIfJcrMapping(libraryPath, resourceResolver);
+        if (StringUtils.isEmpty(clientLibraryPath)) {
+            clientLibraryPath = resolvePathIfProxied(libraryType, libraryPath, resourceResolver);
+        }
+        return clientLibraryPath;
+    }
+
+    private String resolvePathIfJcrMapping(String libraryPath, ResourceResolver resourceResolver) {
```
Comment (kwin) [inline bundle/src/main/java/com/adobe/acs/commons/rewriter/impl/VersionedClientlibsTransformerFactory.java:289]: The method name is a bit off as you always do the mapping. I would prefer `resolvePath`, also I think the methods `resolvePath` and `resolvePathIfJcrMapping` should be merged into one.

**Review by kwin — CHANGES_REQUESTED** [review]
Thanks for the PR. I added some remarks.

File: bundle/src/main/java/com/adobe/acs/commons/rewriter/impl/VersionedClientlibsTransformerFactory.java (hunk 1 above)
Comment (pcastelog) [reply bundle/src/main/java/com/adobe/acs/commons/rewriter/impl/VersionedClientlibsTransformerFactory.java]: I passed the request through the methods till the new one that I added

File: bundle/src/main/java/com/adobe/acs/commons/rewriter/impl/VersionedClientlibsTransformerFactory.java (hunk 2 above)
Comment (pcastelog) [reply bundle/src/main/java/com/adobe/acs/commons/rewriter/impl/VersionedClientlibsTransformerFactory.java]: Methods merged in one "resolvePath" that will take care of JCR resolve and If Proxied

**Review by davidjgonzalez — APPROVED** [review]

**Review by kwin — APPROVED** [review]
