### PR TITLE
handle case where SlingBindings is null. fixes #2228

### LINKED ISSUE #2228: SlingBindings is null and results in NullPointerException in usage with @SlingServlet
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.4.7
* [x] ACS AEM Commons Version: 4.4.2 / 4.4.3-SNAPSHOT
* [x] Reproducible on Latest? yes

### Expected Behavior
In case of using a @SlingServlet to resolve a request to a Sling model with a @ChildResourceFromRequest(injectionStrategy ...) the class OverridePathSlingRequestWrapper should not throw a NullPointerException.

### Actual Behavior
The class OverridePathSlingRequestWrapper throws a NullPointerException at:
`SlingBindings slingBindings = (SlingBindings) getSlingRequest().getAttribute(ATTR_SLING_BINDINGS);`
------------------------vvvvvvvvvvvv is null
`this.adapterManager = slingBindings.getSling().getService(AdapterManager.class);`

This happens because because no SlingBindings is found in case of usage of @SlingServlet with SlingModel with ChildResourceFromRequest

### Steps to Reproduce
- Create a @SlingServlet with `extends SlingAllMethodsServlet` e.g.:
`    @Override
    protected final void doPost(final SlingHttpServletRequest request, final SlingHttpServletResponse response)
        throws IOException {
       MySlingModelWithChildResource model = request.adaptTo(MySlingModelWithChildResource.class);
`
- Have a field in the MySlingModelWithChildResource like:
`
    @ChildResourceFromRequest(injectionStrategy = InjectionStrategy.OPTIONAL)
    private List<MyChildResource> childResource;

`

### Links
Will provide it if needed.

### PR DESCRIPTION
**Pull request by justinedelson**
This is alternative to #2229

### CODE REVIEW

File: bundle/src/test/java/com/adobe/acs/commons/models/injectors/impl/ChildResourceFromRequestInjectorTest.java [hunk 1]
```diff
@@ -34,13 +33,14 @@
...
 import static org.junit.Assert.assertNull;
-import static org.junit.Assert.assertSame;
 
 public class ChildResourceFromRequestInjectorTest {
+
+    private ActivatorHelper activatorHelper = new ActivatorHelper();
+
     @Rule
-    public final AemContext context = new AemContext(ResourceResolverType.JCR_MOCK);
+    public final AemContext context = new AemContext(activatorHelper.afterSetup(), activatorHelper.beforeTeardown(), ResourceResolverType.JCR_MOCK);
```
Comment (justinedelson) [inline bundle/src/test/java/com/adobe/acs/commons/models/injectors/impl/ChildResourceFromRequestInjectorTest.java]: @stefanseifert can you suggest a better way to do this? Basically I need to invoke these methods whenever the context is created. This approach seems to work fine, but it seems a bit inelegant. I thought about creating a custom subclass of `AemContextImpl` but that would mean a fair bit of duplication from `AemContext`.

**Comment by davidjgonzalez** [comment]
@justinedelson  we good to pull this into the next release? If @stefanseifert has ideas how to clean up the Unit Test, i expect its not a problem to clean it up later?

**Comment by justinedelson** [comment]
yep. I'll be happy to get @stefanseifert 's advice at a later point. Purely about testing so easy enough to change later.
