### PR TITLE
Resolves #2733 by removing implementation of workitem and workflowsession

### LINKED ISSUE #2733: Replace implementation of WorkItem and Workflow Session
## Required Information

* [ 6.5.8 ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: _______
* [ 5.0.14 ] ACS AEM Commons Version: _____
* [ yes ] Reproducible on Latest? yes/no

### Expected Behavior

When building through CM, this codebase should successfully build.

### Actual Behavior

When building through CM, CQBP:84 is being triggered for any classes implementing WorkItem or WorkflowSession. 

### Steps to Reproduce

Try building this codebase through CloudManager, and you'll get a CSV containing issues with CQBP:84 being cited.

### Links

https://experienceleague.adobe.com/docs/experience-manager-cloud-manager/using/how-to-use/custom-code-quality-rules.html?lang=en#oakpal-rules

### PR DESCRIPTION
**Pull request by froggin**

### CODE REVIEW

File: bundle/src/main/java/com/adobe/acs/commons/workflow/synthetic/impl/cq/SyntheticWorkItem.java [hunk 1]
```diff
@@ -43,22 +49,51 @@
...
+                return getWorkflowData();
+            case "getCurrentAssignee":
+                return getCurrentAssignee();
+            case "getMetaData":
+                return getMetaData();
+            case "getMetaDataMap":
+                return getMetaDataMap();
+            default:
+                LOG.error("CQ SYNTHETICWORKFLOW ITEM >> NO IMPLEMENTATION FOR {}", methodName);
+                throw new UnsupportedOperationException();
```
Comment (kwin) [inline bundle/src/main/java/com/adobe/acs/commons/workflow/synthetic/impl/cq/SyntheticWorkItem.java:85]: Either log or throw. In this case I would suggest to throw with a meaningful message.

File: bundle/src/main/java/com/adobe/acs/commons/workflow/synthetic/impl/cq/SyntheticWorkflow.java [hunk 2]
```diff
@@ -62,7 +63,7 @@ public final String getId() {
 
     @Override
     public final List<WorkItem> getWorkItems() {
-        return Arrays.asList(new WorkItem[]{this.activeWorkItem});
+        return Arrays.asList(new WorkItem[]{(WorkItem)this.activeWorkItem});
```
Comment (kwin) [inline bundle/src/main/java/com/adobe/acs/commons/workflow/synthetic/impl/cq/SyntheticWorkflow.java:66]: https://docs.oracle.com/javase/8/docs/api/java/util/Collections.html#singletonList-T-

File: bundle/src/main/java/com/adobe/acs/commons/workflow/synthetic/impl/granite/SyntheticWorkItem.java [hunk 3]
```diff
@@ -43,34 +50,73 @@
...
+            case "setPriority":
+                setPriority((InboxItem.Priority) args[0]);
+                return new Object();
+            case "setTimeEnded":
+                this.setTimeEnded((Date) args[0]);
+                return new Object();
+            case "getMetaDataMap":
+                return getMetaDataMap();
+            default:
+                LOG.error("GRANITE SYNTHETICWORKFLOW ITEM >> NO IMPLEMENTATION FOR {}", methodName);
```
Comment (kwin) [inline bundle/src/main/java/com/adobe/acs/commons/workflow/synthetic/impl/granite/SyntheticWorkItem.java:99]: either log or throw

File: bundle/src/main/java/com/adobe/acs/commons/workflow/synthetic/impl/granite/SyntheticWorkflow.java [hunk 4]
```diff
@@ -60,7 +61,7 @@ public final String getId() {
 
     @Override
     public final List<WorkItem> getWorkItems() {
-        return Arrays.asList(new WorkItem[]{this.activeWorkItem});
+        return Arrays.asList(new WorkItem[]{(WorkItem)this.activeWorkItem});
```
Comment (kwin) [inline bundle/src/main/java/com/adobe/acs/commons/workflow/synthetic/impl/granite/SyntheticWorkflow.java:64]: https://docs.oracle.com/javase/8/docs/api/java/util/Collections.html#singletonList-T-

File: bundle/src/main/java/com/adobe/acs/commons/workflow/synthetic/impl/granite/SyntheticWorkflowSession.java [hunk 5]
```diff
@@ -74,7 +76,84 @@ public SyntheticWorkflowSession(SyntheticWorkflowRunnerImpl workflowService, Ses
...
+            case "logout":
+                logout();
+                return new Object();
+            case "isSuperuser":
+                return isSuperuser();
+            case "restartWorkflow":
+                restartWorkflow((Workflow) args[0]);
+                return new Object();
+            default:
+                log.error("SYNTHETICWORKFLOW SESSION >> NO IMPLEMENTATION FOR {}", methodName);
```
Comment (kwin) [inline bundle/src/main/java/com/adobe/acs/commons/workflow/synthetic/impl/granite/SyntheticWorkflowSession.java:152]: log or throw

File: bundle/src/main/java/com/adobe/acs/commons/workflow/synthetic/impl/granite/SyntheticWorkflowSession.java [hunk 6]
```diff
@@ -74,7 +76,84 @@ public SyntheticWorkflowSession(SyntheticWorkflowRunnerImpl workflowService, Ses
...
 
-    @Override
+    public static SyntheticWorkflowSession createSyntheticWorkflowSession(SyntheticWorkflowRunnerImpl workflowService, Session session) {
+        return new SyntheticWorkflowSession(workflowService, session);
+    }
+
+    @Override
+    public Object invoke(Object proxy, Method method, Object[] args) throws Throwable {
+        String methodName = method.getName();
+        switch (methodName) {
```
Comment (kwin) [inline bundle/src/main/java/com/adobe/acs/commons/workflow/synthetic/impl/granite/SyntheticWorkflowSession.java:86]: all methods which just throw UOE can be removed, as the handling is done already in the default branch.

Comment (froggin) [reply bundle/src/main/java/com/adobe/acs/commons/workflow/synthetic/impl/granite/SyntheticWorkflowSession.java:86]: @kwin I updated how this is handled (removed it) so please let me know if that is sufficient.

File: bundle/src/main/java/com/adobe/acs/commons/wcm/vanity/impl/ExtensionlessRequestWrapper.java [hunk 7]
```diff
@@ -20,65 +20,12 @@
...
 import org.apache.sling.api.SlingHttpServletRequest;
-import org.apache.sling.api.request.RequestPathInfo;
-import org.apache.sling.api.resource.Resource;
-import org.apache.sling.api.resource.ValueMap;
 import org.apache.sling.api.wrappers.SlingHttpServletRequestWrapper;
 
-public class ExtensionlessRequestWrapper extends SlingHttpServletRequestWrapper {
 
-    private static final String SLING_STATUS = "sling:status";
+public class ExtensionlessRequestWrapper extends SlingHttpServletRequestWrapper {
```
Comment (kwin) [inline bundle/src/main/java/com/adobe/acs/commons/wcm/vanity/impl/ExtensionlessRequestWrapper.java:26]: what does this empty wrapper do now? IMHO all methods just delegate.... Can't we remove then the whole wrapper?

Comment (froggin) [reply bundle/src/main/java/com/adobe/acs/commons/wcm/vanity/impl/ExtensionlessRequestWrapper.java:26]: Agreed -- I'm thinking I should re-work that PR to function more like the work done in this one. Thoughts?

Comment (adamcin) [reply bundle/src/main/java/com/adobe/acs/commons/wcm/vanity/impl/ExtensionlessRequestWrapper.java:26]: can you rebase this PR to exclude the RequestPathInfo changes that are present in the other PR?

Comment (froggin) [reply bundle/src/main/java/com/adobe/acs/commons/wcm/vanity/impl/ExtensionlessRequestWrapper.java]: Rebased/removed the other stuff.

File: bundle/src/main/java/com/adobe/acs/commons/workflow/synthetic/impl/granite/SyntheticWorkflowSession.java [hunk 8]
```diff
@@ -163,155 +149,32 @@ public final WorkflowModel getModel(final String modelId) throws WorkflowExcepti
...
-            if (this.session != null) {
-                try {
-                    return (AdapterType) workflowService.getResourceResolver(session);
-                } catch (LoginException e) {
-                    log.error("Failed to adapt Synthetic Granite WorkflowSession to ResourceResolver", e);
-                }
-            }
-        } else if (Session.class == type) {
-            return (AdapterType) this.session;
+    public Object adaptTo(Class<?> type) {
```
Comment (davidjgonzalez) [inline bundle/src/main/java/com/adobe/acs/commons/workflow/synthetic/impl/granite/SyntheticWorkflowSession.java:175]: Any reason why this is not adaptable to a ResourceResolver anymore?

File: bundle/src/main/java/com/adobe/acs/commons/workflow/synthetic/impl/granite/SyntheticWorkflowSession.java [hunk 9]
```diff
@@ -74,86 +65,81 @@ public SyntheticWorkflowSession(SyntheticWorkflowRunnerImpl workflowService, Ses
...
-    public final ResultSet<WorkflowModel> getModels(final long l, final long l2) throws WorkflowException {
-        throw new UnsupportedOperationException(UNSUPPORTED_OPERATION_MESSAGE);
-    }
-
-    @Override
-    public final ResultSet<WorkflowModel> getModels(final long l, final long l2,
-                                                    final WorkflowModelFilter workflowModelFilter)
-            throws WorkflowException {
-        throw new UnsupportedOperationException(UNSUPPORTED_OPERATION_MESSAGE);
+    public final Object getModel(Object[] args) throws WorkflowException {
```
Comment (davidjgonzalez) [inline bundle/src/main/java/com/adobe/acs/commons/workflow/synthetic/impl/granite/SyntheticWorkflowSession.java:135]: Just curious - this looks like a net-new method signature for getModel(..) was this somehow missed before..?
I dont see it in the original impl, but maybe im missing it in the diff somewhere :)

File: bundle/src/main/java/com/adobe/acs/commons/workflow/synthetic/cq/WrappedSyntheticWorkItem.java [hunk 10]
```diff
@@ -0,0 +1,24 @@
...
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ * #L%
+ */
+
+package com.adobe.acs.commons.workflow.synthetic.cq;
+
+public interface WrappedSyntheticWorkItem {
```
Comment (davidjgonzalez) [inline bundle/src/main/java/com/adobe/acs/commons/workflow/synthetic/cq/WrappedSyntheticWorkItem.java:23]: Do these require a package-info version bump? These are exported right?

**Review by davidjgonzalez — COMMENTED** [review]
@froggin thanks!! generally looks good - didn't try it out but IIRC the test coverage was pretty good and if its increased, then even better :) 

Only item that might be a miss is no more adapting to RR..?

File: bundle/src/main/java/com/adobe/acs/commons/workflow/synthetic/impl/granite/SyntheticWorkflowSession.java (hunk 8 above)
Comment (froggin) [reply bundle/src/main/java/com/adobe/acs/commons/workflow/synthetic/impl/granite/SyntheticWorkflowSession.java:175]: Oh, I missed that somehow. I'll add it back in!

File: bundle/src/main/java/com/adobe/acs/commons/workflow/synthetic/impl/granite/SyntheticWorkflowSession.java (hunk 9 above)
Comment (froggin) [reply bundle/src/main/java/com/adobe/acs/commons/workflow/synthetic/impl/granite/SyntheticWorkflowSession.java:135]: `com.adobe.granite.workflow.WorkflowSession` has that in there, so I figured it was probably something I should cover. If we don't need it we can rip that part out.

Comment (davidjgonzalez) [reply bundle/src/main/java/com/adobe/acs/commons/workflow/synthetic/impl/granite/SyntheticWorkflowSession.java:135]: no worries - if it's in there, sall good. was just surprised the prior impl approach wouldve let that slip through!

File: bundle/src/main/java/com/adobe/acs/commons/workflow/synthetic/cq/WrappedSyntheticWorkItem.java (hunk 10 above)
Comment (adamcin) [reply bundle/src/main/java/com/adobe/acs/commons/workflow/synthetic/cq/WrappedSyntheticWorkItem.java:23]: I suppose that this only a minor change at most because these interfaces aren't used by any existing exported type signatures. @froggin we should probably at least add @ProviderType to these Wrapped interfaces.

Comment (adamcin) [reply bundle/src/main/java/com/adobe/acs/commons/workflow/synthetic/cq/WrappedSyntheticWorkItem.java:23]: this is the maven-bundle-plugin:3.4.0:baseline output on a recent version of the master branch, which might indicate that child packages of workflow.synthetic aren't exported: 
```
[INFO] -----------------------------------------------------------------------------------------------------------
[INFO]   com.adobe.acs.commons.workflow                     unchanged  1.1.1      1.1.1      1.1.1      -
[INFO] -----------------------------------------------------------------------------------------------------------
[INFO]   com.adobe.acs.commons.workflow.bulk.execution      unchanged  1.0.1      1.0.1      1.0.1      -
[INFO] -----------------------------------------------------------------------------------------------------------
[INFO]   com.adobe.acs.commons.workflow.bulk.execution.model unchanged  4.0.0      4.0.0      4.0.0      -
[INFO] -----------------------------------------------------------------------------------------------------------
[INFO]   com.adobe.acs.commons.workflow.bulk.removal        unchanged  4.0.0      4.0.0      4.0.0      -
[INFO] -----------------------------------------------------------------------------------------------------------
[INFO]   com.adobe.acs.commons.workflow.synthetic           unchanged  3.0.0      3.0.0      3.0.0      -
[INFO] -----------------------------------------------------------------------------------------------------------
```

Comment (froggin) [reply bundle/src/main/java/com/adobe/acs/commons/workflow/synthetic/cq/WrappedSyntheticWorkItem.java:26]: I just added the `@ProviderType` annotations, and put the ResourceResolver back in the adaptTo method of the granite SyntheticWorkflowSession

**Review by davidjgonzalez — APPROVED** [review]
I will check package exports and bump package-info if necessary
